### ISSUE TITLE
High current traces are suspiciously thin

### ISSUE THREAD

**Issue by napowderly** [Timot05/cypd3177-usb-pd#1]
![Screenshot 2024-04-19 at 2 07 02 PM](https://github.com/Timot05/cypd3177-usb-pd/assets/8122613/dc31105e-ce85-41bf-84e6-7b75139902a0)

I would probably either use pours or just try squeeze some nice fat boi traces in there. 5A will be spicy with .25mm traces.

**Comment by Timot05** [comment]
Added pours!
